server:
  port: 8082
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          password: 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
          uri: https://github.com/flopcoder82/microservices
          username: developer7823
